# Generated by Django 5.0.1 on 2024-02-04 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('event_id', models.BigAutoField(default=100000, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='featured_images/')),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('speaker_names', models.CharField(max_length=200)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_online', models.BooleanField(default=False)),
                ('video_link', models.URLField(blank=True, null=True)),
                ('seats_available', models.IntegerField(blank=True, null=True)),
                ('last_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
