# Generated by Django 5.0.1 on 2024-02-13 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdetails',
            old_name='speaker_names',
            new_name='speaker_name',
        ),
    ]
