# Generated by Django 5.0.1 on 2024-02-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminuser', '0002_rename_speaker_names_eventdetails_speaker_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='event_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
